### ISSUE TITLE
카테고리 다운로드 기능이 정상작동 하지 않는거 같습니다.

### ISSUE THREAD

**Issue by ytoaa** [A121321231232/naver-blog-original-image-crawler#1]
개별 다운은 잘되는데
카테고리로 하면 FileNotFoundError 가 뜨네요

**Comment by ytoaa** [comment]
자문 자답입니다...
이야 투명 특수문자 하나가 이렇게...
" " 큰 따음표 안에 있는 한글자 특수문자만
46번줄 re.sub에 추가했습니다.

**Comment by A121321231232** [comment]
폴더 이름 양 끝에 공백이 있으면 에러가 생기는 것 같아서 양 끝의 공백을 제거하도록 고쳤습니다
