### ISSUE TITLE
건의) 카테고리 링크로 다운로드, 큰 카테고리 다운로드

### ISSUE THREAD

**Issue by heonchul** [A121321231232/naver-blog-original-image-crawler#2]
우선 좋은 코드 공유해주셔서 정말 감사드립니다!
덕분에 굉장히 시간단축에 큰 도움이 되었습니다.

잘 쓰는 데 그 중에서 제일 필요하다고 생각하는 두가지 기능을 건의드리고자 이렇게 글을 작성합니다.
첫째, 게시글 링크가 아닌 카테고리 링크로 '카테고리 다운로드' 기능을 쓸 수 있을 것
둘째, 큰 카테고리(하부 카테고리를 포함한 상태) 도 다운 가능할 것

1. 현재 '카테고리 다운로드'를 할 때, (카테고리 안에 있는) 게시글 링크를 이용하여 하게 되는데
게시글 링크 말고 카테고리 링크를 넣어 사용하면 더욱 편하게 사용할 것 같습니다.
게시글 링크를 얻으려면 '카테고리 클릭(이동) -> 게시글 링크 복사' 순으로 이루어지는 데 반해
카테고리 링크는 페이지 이동을 하지 않아도 바로 링크를 얻을 수 있기 때문입니다.

2. 큰 카테고리 상태로는 못받기 때문에, 작은 카테고리 하나하나 찾아가서  링크를 얻는 것에 비하면 더욱 편할 것 같습니다.
한번 알아본 바로는 카테고리를 폴더처럼 인식하는 듯 합니다.
큰 카테고리에 속하지만, 작은 카테고리에 속하지 않는 독립된 게시글을 카테고리 다운에 넣고 돌렸을 때
독립된 게시글 끼리 다운받아지더라구요.

Ex) 큰 카테고리 (A) 내부에 작은 카테고리 (a)가 있다.
A는 10개, a는 7개의 게시물을 가질 때 
A에는 속하지만 a에는 속하지 않은 3개의 게시물끼리 다운된다.

어디까지나 건의사항이고, 구현에 어려움이 있을 수도 있지만
추가해 주신다면 정말 감사히 쓰겠습니다.
감사합니다!

**Comment by A121321231232** [comment]
일단 기능을 추가해 보았는데 혹시 버그가 있거나 프로그램이 갑자기 꺼지거나 하면 말해 주세요
