### ISSUE TITLE
이미 다운로드된 파일은 건너띄는 기능은 없을까요?

### ISSUE THREAD

**Issue by ytoaa** [A121321231232/naver-blog-original-image-crawler#3]
스크립트를 매우 잘 쓰고있습니다.
다만 매번 처음부터 다운받기에
혹시나 기존에 다운받은 애들은 건너띄는 기능은 없을까요?

**Comment by A121321231232** [comment]
중복되는 폴더를 건너뛰는 기능이 필요하신 건가요 아니면 중복되는 이미지를 건너뛰는 기능이 필요하신 건가요?

**Comment by ytoaa** [comment]
> 중복되는 폴더를 건너뛰는 기능이 필요하신 건가요 아니면 중복되는 이미지를 건너뛰는 기능이 필요하신 건가요?

이미지의 크기,이름 비교로 건너뛰는 기능이 필요합니다.

**Comment by A121321231232** [comment]
이미지의 이름과 바이트 수를 비교해서 중복되는 이미지는 건너뛰도록 기능을 추가했습니다.
혹시 예기치 못한 문제가 발생하면 알려 주세요.

**Comment by ytoaa** [comment]
> 이미지의 이름과 바이트 수를 비교해서 중복되는 이미지는 건너뛰도록 기능을 추가했습니다. 혹시 예기치 못한 문제가 발생하면 알려 주세요.

폴더중 맨끝에 마침표가 들어가면 윈도우에서는 폴더 글자가 깨지네요
리눅스 환경에서는 정상적으로 폴더 이름이 출력됩니다.

**Comment by A121321231232** [comment]
깨지는 링크랑 다운받을 때 설정을 알려주실 수 있나요

**Comment by ytoaa** [comment]
> 깨지는 링크랑 다운받을 때 설정을 알려주실 수 있나요

리눅스에서 실행후 해당 다운로드된 폴더를 smb로 윈도우와 공유했을때 발생했습니다.
리눅스랑 윈도우의 폴더 이름 생성에서의 차이때문인거 같네요

https://m.blog.naver.com/PostList.naver?blogId=zoncrown&categoryNo=22&logCode=0

**Comment by A121321231232** [comment]
> > 깨지는 링크랑 다운받을 때 설정을 알려주실 수 있나요
> 
> 리눅스에서 실행후 해당 다운로드된 폴더를 smb로 윈도우와 공유했을때 발생했습니다. 리눅스랑 윈도우의 폴더 이름 생성에서의 차이때문인거 같네요
> 
> https://m.blog.naver.com/PostList.naver?blogId=zoncrown&categoryNo=22&logCode=0

https://m.blog.naver.com/PostView.naver?blogId=zoncrown&logNo=222973001367&navType=by
이 게시글에서 에러가 나던데 폴더 이름 끝에 마침표가 있으면 삭제되게 업데이트했습니다
윈도우에서 폴더 이름에 사용할 수 없는 문자 외에도 폴더 이름 끝에 마침표가 있으면 알아서 삭제되더라고요
이제 다운받을 때 미리 끝에서 마침표를 없애니까 아마 괜찮을 겁니다

**Comment by ytoaa** [comment]
> > > 깨지는 링크랑 다운받을 때 설정을 알려주실 수 있나요
> > 
> > 
> > 리눅스에서 실행후 해당 다운로드된 폴더를 smb로 윈도우와 공유했을때 발생했습니다. 리눅스랑 윈도우의 폴더 이름 생성에서의 차이때문인거 같네요
> > https://m.blog.naver.com/PostList.naver?blogId=zoncrown&categoryNo=22&logCode=0
> 
> https://m.blog.naver.com/PostView.naver?blogId=zoncrown&logNo=222973001367&navType=by 이 게시글에서 에러가 나던데 폴더 이름 끝에 마침표가 있으면 삭제되게 업데이트했습니다 윈도우에서 폴더 이름에 사용할 수 없는 문자 외에도 폴더 이름 끝에 마침표가 있으면 알아서 삭제되더라고요 이제 다운받을 때 미리 끝에서 마침표를 없애니까 아마 괜찮을 겁니다

정말 감사합니다.
